- hosts: manager
  become: true
  roles:
  - docker
  - manager

- hosts: worker
  become: true
  roles:
  - docker
  - role: worker
    vars:
      manager: projectm

- hosts: nginx
  become: true
  roles:
  - docker
  - nginx
 
