---
    - name: add jenkins user
      user:
        name: jenkins
        groups: docker
        shell: /bin/bash
        append: true

    - name: "docker swarm activate"
      community.general.docker_swarm:
        state: present
      register: swarm_info
